version: '3.8'

services:
  database:
    build: 
      context: ./db
      dockerfile: Dockerfile.bd
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: tg_user
      POSTGRES_PASSWORD: 8520
    networks:
      - mynetwork
    ports:
      - "5432:5432"

  db_replica:
    build: 
      context: ./db_repl
      dockerfile: Dockerfile.repl
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: tg_user
      POSTGRES_PASSWORD: 8520
    networks:
      - mynetwork
    depends_on:
      - database
    ports:
      - "5433:5432"  

  bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile.bot
    env_file:
      - token.env 
    environment:
      DATABASE_URL: postgres://tg_user:8520@database:5432/bot_db
    depends_on:
      - database
      - db_replica 
    networks:
      - mynetwork

networks:
  mynetwork:
