[database]
db_server ansible_host=192.168.206.140  ansible_user=root ansible_password=8520

[bot]
bot_server ansible_host=192.168.206.155

[database_repl]
database_repl ansible_host=192.168.206.155


